apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconfig-blog
  labels:
    app: appconfig-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appconfig-blog
  template:
    metadata:
      labels:
        app: appconfig-blog
    spec:
      containers:
        - name: my-app
          image: 318168271290.dkr.ecr.us-east-1.amazonaws.com/blog-appconfig-eks:latest
          imagePullPolicy: IfNotPresent
        - name: appconfig-agent
          image: public.ecr.aws/aws-appconfig/aws-appconfig-agent:2.x
          ports:
            - name: http
              containerPort: 2772
              protocol: TCP
          env:
            - name: us-east-1
              value: region
          imagePullPoliy: IfNotPresent
